application: playii
version: 1
runtime: python
api_version: 1
#default_expiration: "10d"

handlers:

# 51.html -> html_p3p.py :: 51 needs p3p header to set cookie
#- url: /chat/51\.html
#  script: p3p_header.py

#### static directories

- url: /ajax
  static_dir: ajax

- url: /client
  static_dir: client

#### default handler

- url: /.*
  script: not_found.py