application: playii
api_version: 1
runtime: python
version: 1

#default_expiration: "10d"

handlers:

- url: /
  static_files: html/index.html
  upload: html/index.html
- url: /favicon.ico
  static_files: html/favicon.ico
  upload: html/favicon.ico

- url: /html
  static_dir: html

- url: /app
  static_dir: app
- url: /client
  static_dir: app

- url: /.*
  script: util/not_found.py

