application: local-static-html-iphone
version: 1
runtime: python
api_version: 1
#default_expiration: "10d"

handlers:

#### static directories

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /image
  static_dir: image

- url: /html
  static_dir: html

- url: /(.*\.(html))
  static_files: html/\1
  upload: html/(.*\.(html))

#### default handler

- url: /.*
  script: not_found.py
